"""Extraction schemas per document type for LLM field extraction."""
from typing import Any, Dict

DOCUMENT_TYPE_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "CMR": {
        "type": "object",
        "properties": {
            "shipper_name": {"type": "string"},
            "shipper_address": {"type": "string"},
            "consignee_name": {"type": "string"},
            "consignee_address": {"type": "string"},
            "date_of_consignment": {"type": "string"},
            "place_of_consignment": {"type": "string"},
            "reference_number": {"type": "string"},
            "goods_description": {"type": "string"},
            "quantity": {"type": "string"},
            "weight": {"type": "string"},
        },
    },
    "INVOICE": {
        "type": "object",
        "properties": {
            "invoice_number": {"type": "string"},
            "invoice_date": {"type": "string"},
            "seller_name": {"type": "string"},
            "buyer_name": {"type": "string"},
            "total_amount": {"type": "string"},
            "currency": {"type": "string"},
            "tax_amount": {"type": "string"},
            "items": {"type": "array"},
        },
    },
    "DELIVERY_NOTE": {
        "type": "object",
        "properties": {
            "delivery_note_number": {"type": "string"},
            "delivery_date": {"type": "string"},
            "recipient_name": {"type": "string"},
            "recipient_address": {"type": "string"},
            "items": {"type": "array"},
        },
    },
    "BILL_OF_LADING": {
        "type": "object",
        "properties": {
            "bl_number": {"type": "string"},
            "shipper_name": {"type": "string"},
            "shipper_address": {"type": "string"},
            "consignee_name": {"type": "string"},
            "consignee_address": {"type": "string"},
            "notify_party": {"type": "string"},
            "vessel_name": {"type": "string"},
            "voyage_number": {"type": "string"},
            "port_of_loading": {"type": "string"},
            "port_of_discharge": {"type": "string"},
            "place_of_delivery": {"type": "string"},
            "goods_description": {"type": "string"},
            "container_numbers": {"type": "array"},
            "weight": {"type": "string"},
            "number_of_packages": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "AIR_WAYBILL": {
        "type": "object",
        "properties": {
            "awb_number": {"type": "string"},
            "shipper_name": {"type": "string"},
            "shipper_address": {"type": "string"},
            "consignee_name": {"type": "string"},
            "consignee_address": {"type": "string"},
            "airport_of_departure": {"type": "string"},
            "airport_of_destination": {"type": "string"},
            "flight_number": {"type": "string"},
            "goods_description": {"type": "string"},
            "weight": {"type": "string"},
            "number_of_pieces": {"type": "string"},
            "declared_value": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "SEA_WAYBILL": {
        "type": "object",
        "properties": {
            "swb_number": {"type": "string"},
            "shipper_name": {"type": "string"},
            "consignee_name": {"type": "string"},
            "notify_party": {"type": "string"},
            "vessel_name": {"type": "string"},
            "voyage_number": {"type": "string"},
            "port_of_loading": {"type": "string"},
            "port_of_discharge": {"type": "string"},
            "goods_description": {"type": "string"},
            "weight": {"type": "string"},
            "number_of_packages": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "PACKING_LIST": {
        "type": "object",
        "properties": {
            "packing_list_number": {"type": "string"},
            "date": {"type": "string"},
            "shipper_name": {"type": "string"},
            "consignee_name": {"type": "string"},
            "items": {"type": "array"},
            "total_packages": {"type": "string"},
            "gross_weight": {"type": "string"},
            "net_weight": {"type": "string"},
            "dimensions": {"type": "string"},
            "marks_and_numbers": {"type": "string"},
        },
    },
    "CUSTOMS_DECLARATION": {
        "type": "object",
        "properties": {
            "declaration_number": {"type": "string"},
            "declaration_type": {"type": "string"},
            "importer_name": {"type": "string"},
            "exporter_name": {"type": "string"},
            "country_of_origin": {"type": "string"},
            "country_of_destination": {"type": "string"},
            "hs_codes": {"type": "array"},
            "goods_description": {"type": "string"},
            "customs_value": {"type": "string"},
            "currency": {"type": "string"},
            "duty_amount": {"type": "string"},
            "date_of_declaration": {"type": "string"},
        },
    },
    "CERTIFICATE_OF_ORIGIN": {
        "type": "object",
        "properties": {
            "certificate_number": {"type": "string"},
            "exporter_name": {"type": "string"},
            "exporter_address": {"type": "string"},
            "consignee_name": {"type": "string"},
            "consignee_address": {"type": "string"},
            "country_of_origin": {"type": "string"},
            "goods_description": {"type": "string"},
            "quantity": {"type": "string"},
            "weight": {"type": "string"},
            "issuing_authority": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "DANGEROUS_GOODS_DECLARATION": {
        "type": "object",
        "properties": {
            "dgd_number": {"type": "string"},
            "shipper_name": {"type": "string"},
            "consignee_name": {"type": "string"},
            "un_number": {"type": "string"},
            "proper_shipping_name": {"type": "string"},
            "hazard_class": {"type": "string"},
            "packing_group": {"type": "string"},
            "quantity": {"type": "string"},
            "weight": {"type": "string"},
            "emergency_contact": {"type": "string"},
            "transport_mode": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "FREIGHT_BILL": {
        "type": "object",
        "properties": {
            "freight_bill_number": {"type": "string"},
            "shipper_name": {"type": "string"},
            "consignee_name": {"type": "string"},
            "origin": {"type": "string"},
            "destination": {"type": "string"},
            "goods_description": {"type": "string"},
            "weight": {"type": "string"},
            "freight_charges": {"type": "string"},
            "currency": {"type": "string"},
            "surcharges": {"type": "string"},
            "total_amount": {"type": "string"},
            "date_of_issue": {"type": "string"},
        },
    },
    "UNKNOWN": {
        "type": "object",
        "properties": {
            "document_title": {"type": "string"},
            "document_number": {"type": "string"},
            "date": {"type": "string"},
            "sender_name": {"type": "string"},
            "sender_address": {"type": "string"},
            "recipient_name": {"type": "string"},
            "recipient_address": {"type": "string"},
            "description": {"type": "string"},
            "total_amount": {"type": "string"},
            "reference_numbers": {"type": "array"},
        },
    },
}


def get_extraction_schema(document_type: str) -> Dict[str, Any]:
    """Return the extraction schema for the given document type."""
    return DOCUMENT_TYPE_SCHEMAS.get(document_type, DOCUMENT_TYPE_SCHEMAS["UNKNOWN"])
