from uuid import UUID

from ...domain.entities.validation_result import ValidationResult, ValidationStatus
from ...domain.services.validation_engine import ValidationEngine
from ...infrastructure.persistence.repositories import (
    DocumentRepository, ExtractionRepository, ValidationResultRepository
)
from ...application.dtos.validation_dto import ValidationResultDTO


class ValidateDataUseCase:
    """Use case for validating extracted data"""
    
    def __init__(
        self,
        document_repository: DocumentRepository,
        extraction_repository: ExtractionRepository,
        validation_result_repository: ValidationResultRepository,
        validation_engine: ValidationEngine,
    ):
        self.document_repository = document_repository
        self.extraction_repository = extraction_repository
        self.validation_result_repository = validation_result_repository
        self.validation_engine = validation_engine
    
    def execute(self, document_id: UUID) -> ValidationResultDTO:
        """
        Validate extracted data.
        
        Args:
            document_id: Document ID
        
        Returns:
            ValidationResultDTO
        """
        # Get document
        document = self.document_repository.get_by_id(document_id)
        if not document:
            raise ValueError(f"Document {document_id} not found")
        
        # Get extraction
        extraction = self.extraction_repository.get_by_document_id(document_id)
        if not extraction:
            raise ValueError(f"Extraction not found for document {document_id}")
        
        # Run validation
        errors = self.validation_engine.validate(
            document.document_type,
            extraction.structured_data
        )
        
        # Determine status
        status = self.validation_engine.get_validation_status(errors)
        
        # Create validation result
        validation_result = ValidationResult(
            id=UUID(int=0),  # Will be generated by repository
            extraction_id=extraction.id,
            validation_rules={"document_type": document.document_type.value},
            validation_status=status,
            validation_errors=errors,
        )
        
        # Save validation result
        saved_result = self.validation_result_repository.create(validation_result)
        
        # Convert to DTO
        return ValidationResultDTO(
            id=saved_result.id,
            extraction_id=saved_result.extraction_id,
            validation_rules=saved_result.validation_rules,
            validation_status=saved_result.validation_status,
            validation_errors=[
                {"field": e.field, "message": e.message, "severity": e.severity}
                for e in saved_result.validation_errors
            ],
            validated_at=saved_result.validated_at,
        )

